name: Build

permissions: write-all

on:
  push:
    branches: [ "main", "*.*" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main", "*.*" ]
  workflow_dispatch:

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Update repository
      run: apt-get update -y

    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++

    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: |
        chmod -x debian/lingmo-*
        dpkg-buildpackage -b -uc -us -j$(nproc)
        mkdir -p artifacts
        cp -rfv ../*.deb ./artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: Lingmo Artifacts
        path: artifacts
        compression-level: 9 # maximum compression
